### ISSUE TITLE
Accélération de la saisie

### ISSUE THREAD

**Issue by nicolaspoulain** [chardetm/capytale-rich-text-editor#2]
Si on charge (beaucoup, certes) le contenu de l'éditeur Lexical, on observe un ralentissement de la saisie.
L'évènement onChange doit-il déclencher à chaque frappe le production du json serialisé et de la traduction du html ?
Ne faudrait-il pas produire ces contenus à l'enregistrement seulement ?

**Comment by chardetm** [comment]
Le dernier commit permet de faire ça avec un contexte, voir exemple dans https://github.com/chardetm/test-capytale-rich-text-editor/ !
